import moment from "moment";
import { Event, Favorite } from "@/types";

export const DummyItinearryInDays: any[] = [
  [
    {
      name: "Barry Can't Swim",
      short: "barryc(1)",
      start: moment("2024-06-28T13:00:00.000Z"),
      end: moment("2024-06-28T13:45:00.000Z"),
      mbId: "7dcf3b98-701a-4309-a90c-eb4179b96ea9",
      id: "e22a03a7723fe77a2a39d6db133aebb44bb1c820ec42e683816882220ae6f7be",
      location: "The Park",
    },
    {
      name: "Confidence Man",
      short: "confid(1)",
      start: moment("2024-06-28T13:15:00.000Z"),
      end: moment("2024-06-28T14:15:00.000Z"),
      mbId: "9fab430a-f1af-4a69-bf68-6857a7a50a68",
      id: "b681eea002186e7d3e25cdb84338e8f8c69f2295641c2bae99052eab6c0e0fe7",
      location: "Other Stage",
    },
    {
      name: "Bombay Bicycle Club",
      short: "bombay1(1)",
      start: moment("2024-06-28T16:15:00.000Z"),
      end: moment("2024-06-28T17:15:00.000Z"),
      mbId: "0ae49abe-d6af-44fa-8ab0-b9ace5690e6f",
      id: "be2235148381e116a96b57f235c6333c3f5f8113a50a93a73f3a54b91bf9bd89",
      location: "Other Stage",
    },
    {
      name: "Arlo Parks",
      short: "arlopa(1)",
      start: moment("2024-06-28T17:00:00.000Z"),
      end: moment("2024-06-28T18:00:00.000Z"),
      id: "6e84f481ca59fa0b73326b22e30d99732d31951831c361f328956cc5ec166bab",
      location: "Woodsies - Main Stage",
    },
    {
      name: "Jamie XX",
      short: "jamiex(1)",
      start: moment("2024-06-28T21:30:00.000Z"),
      end: moment("2024-06-28T22:45:00.000Z"),
      id: "7f3d75179e62b6f218ab9c70f7284f94c730d943a33246b7aeeb686184895ba9",
      location: "Woodsies - Main Stage",
    },
  ],
  [
    {
      name: "Bloc Party",
      short: "blocpa(1)",
      start: moment("2024-06-29T16:30:00.000Z"),
      end: moment("2024-06-29T17:30:00.000Z"),
      mbId: "8c538f11-c141-4588-8ecb-931083524186",
      id: "b8f1eff79a967b07fba7d959daf5fe50892d0ceee8d85c2786610f03abe1f6f0",
      location: "Other Stage",
    },
    {
      name: "The Streets",
      short: "street(1)",
      start: moment("2024-06-29T19:45:00.000Z"),
      end: moment("2024-06-29T20:45:00.000Z"),
      id: "b89edc2f09aa0324c1b76c6f122d83cd4faeaac8b3b455801adea5709d211722",
      location: "Other Stage",
    },
    {
      name: "Disclosure",
      short: "disclo(1)",
      start: moment("2024-06-29T21:30:00.000Z"),
      end: moment("2024-06-29T22:45:00.000Z"),
      id: "9c23a20232f60b07c08a9fc2c79e3e192f01a3e5afca40b60c393bec755faf34",
      location: "Other Stage",
    },
  ],
  [
    {
      name: "Jordan Rakei",
      short: "jordan(1)",
      start: moment("2024-06-30T16:00:00.000Z"),
      end: moment("2024-06-30T17:00:00.000Z"),
      id: "63d18e986a54f60e12d4d0e455358be0783c19bf046fa04750fb254a206f8302",
      location: "West Holts",
    },
    {
      name: "Two Door Cinema Club",
      short: "twodoo(1)",
      start: moment("2024-06-30T18:45:00.000Z"),
      end: moment("2024-06-30T19:45:00.000Z"),
      id: "8c8bafd88cc1d4a8421e9831695633bf448859275856d8e9d35e4601f2f4e039",
      location: "Other Stage",
    },
    {
      name: "Romy",
      short: "romy(1)",
      start: moment("2024-06-30T19:00:00.000Z"),
      end: moment("2024-06-30T20:00:00.000Z"),
      id: "0b8869eaf1e37a9d665a75990b7b9da62046e38d42bf7e558f71a82a19e24bba",
      location: "Woodsies - Main Stage",
    },
    {
      name: "London Grammar",
      short: "london(1)",
      start: moment("2024-06-30T20:15:00.000Z"),
      end: moment("2024-06-30T21:30:00.000Z"),
      id: "6a5d8323a4a85654dec15bf0182bf31eecd0b0215b8821b758749b678cc483af",
      location: "The Park",
    },
  ],
];
export const DummyFavouriteArtists: { [p: string]: Favorite } = {
  "Barry Can't Swim": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/0vTVU0KH0CVzijsoKGsTPl",
      },
      followers: {
        href: null,
        total: 150505,
      },
      genres: ["jazz house"],
      href: "https://api.spotify.com/v1/artists/0vTVU0KH0CVzijsoKGsTPl",
      id: "0vTVU0KH0CVzijsoKGsTPl",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebd81928154288fe971461b05d",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174d81928154288fe971461b05d",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178d81928154288fe971461b05d",
          width: 160,
        },
      ],
      name: "Barry Can't Swim",
      popularity: 60,
      type: "artist",
      uri: "spotify:artist:0vTVU0KH0CVzijsoKGsTPl",
    },
    setName: "Barry Can't Swim",
    relatedArtistName: null,
  },
  "Confidence Man": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/0RwXnFrEoI8tltFvYpJgP6",
      },
      followers: {
        href: null,
        total: 93821,
      },
      genres: ["australian electropop"],
      href: "https://api.spotify.com/v1/artists/0RwXnFrEoI8tltFvYpJgP6",
      id: "0RwXnFrEoI8tltFvYpJgP6",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebf8cb140afe6a47520088581d",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174f8cb140afe6a47520088581d",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178f8cb140afe6a47520088581d",
          width: 160,
        },
      ],
      name: "Confidence Man",
      popularity: 49,
      type: "artist",
      uri: "spotify:artist:0RwXnFrEoI8tltFvYpJgP6",
    },
    setName: "Confidence Man",
    relatedArtistName: null,
  },
  Coldplay: {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU",
      },
      followers: {
        href: null,
        total: 50599622,
      },
      genres: ["permanent wave", "pop"],
      href: "https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU",
      id: "4gzpq5DPGxSnKTe4SA8HAU",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebc878d7a8f8299a3a09e29fb6",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174c878d7a8f8299a3a09e29fb6",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178c878d7a8f8299a3a09e29fb6",
          width: 160,
        },
      ],
      name: "Coldplay",
      popularity: 85,
      type: "artist",
      uri: "spotify:artist:4gzpq5DPGxSnKTe4SA8HAU",
    },
    setName: "Coldplay",
    relatedArtistName: null,
  },
  "Jordan Rakei": {
    track: {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb",
            },
            href: "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
            id: "0cmWgDlu9CwTgxPhf403hb",
            name: "Bonobo",
            type: "artist",
            uri: "spotify:artist:0cmWgDlu9CwTgxPhf403hb",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4KjbNbnTnJ97kZgQkOHr6v",
        },
        href: "https://api.spotify.com/v1/albums/4KjbNbnTnJ97kZgQkOHr6v",
        id: "4KjbNbnTnJ97kZgQkOHr6v",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273226e702d1878d4a44b273980",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02226e702d1878d4a44b273980",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851226e702d1878d4a44b273980",
            width: 64,
          },
        ],
        name: "Fragments",
        release_date: "2022-01-14",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:4KjbNbnTnJ97kZgQkOHr6v",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0cmWgDlu9CwTgxPhf403hb",
          },
          href: "https://api.spotify.com/v1/artists/0cmWgDlu9CwTgxPhf403hb",
          id: "0cmWgDlu9CwTgxPhf403hb",
          name: "Bonobo",
          type: "artist",
          uri: "spotify:artist:0cmWgDlu9CwTgxPhf403hb",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/24icoQNJSEWNu3XvqKBR68",
          },
          href: "https://api.spotify.com/v1/artists/24icoQNJSEWNu3XvqKBR68",
          id: "24icoQNJSEWNu3XvqKBR68",
          name: "Jordan Rakei",
          type: "artist",
          uri: "spotify:artist:24icoQNJSEWNu3XvqKBR68",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "PR",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
      ],
      disc_number: 1,
      duration_ms: 285093,
      explicit: false,
      external_ids: {
        isrc: "GBCFB2100676",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/7aLYQgzGLy8duSSdTJa1ik",
      },
      href: "https://api.spotify.com/v1/tracks/7aLYQgzGLy8duSSdTJa1ik",
      id: "7aLYQgzGLy8duSSdTJa1ik",
      is_local: false,
      name: "Shadows",
      popularity: 53,
      preview_url:
        "https://p.scdn.co/mp3-preview/ac6cfb8894855634c51cf7ae4cefbca0ef886840?cid=7116f40f98d64f5cbb9e2aafb2209702",
      track_number: 2,
      type: "track",
      uri: "spotify:track:7aLYQgzGLy8duSSdTJa1ik",
    },
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/24icoQNJSEWNu3XvqKBR68",
      },
      href: "https://api.spotify.com/v1/artists/24icoQNJSEWNu3XvqKBR68",
      id: "24icoQNJSEWNu3XvqKBR68",
      name: "Jordan Rakei",
      type: "artist",
      uri: "spotify:artist:24icoQNJSEWNu3XvqKBR68",
    },
    setName: "Jordan Rakei",
    relatedArtistName: null,
  },
  "Bloc Party": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/3MM8mtgFzaEJsqbjZBSsHJ",
      },
      followers: {
        href: null,
        total: 1125772,
      },
      genres: [
        "alternative dance",
        "alternative rock",
        "dance-punk",
        "indie rock",
        "indietronica",
        "modern rock",
        "neo-synthpop",
        "new rave",
      ],
      href: "https://api.spotify.com/v1/artists/3MM8mtgFzaEJsqbjZBSsHJ",
      id: "3MM8mtgFzaEJsqbjZBSsHJ",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebaedaa06a45e223f66a686556",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174aedaa06a45e223f66a686556",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178aedaa06a45e223f66a686556",
          width: 160,
        },
      ],
      name: "Bloc Party",
      popularity: 58,
      type: "artist",
      uri: "spotify:artist:3MM8mtgFzaEJsqbjZBSsHJ",
    },
    setName: "Bloc Party",
    relatedArtistName: null,
  },
  "Headie One": {
    track: {
      album: {
        album_type: "SINGLE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6UCQYrcJ6wab6gnQ89OJFh",
            },
            href: "https://api.spotify.com/v1/artists/6UCQYrcJ6wab6gnQ89OJFh",
            id: "6UCQYrcJ6wab6gnQ89OJFh",
            name: "Headie One",
            type: "artist",
            uri: "spotify:artist:6UCQYrcJ6wab6gnQ89OJFh",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2SrSdSvpminqmStGELCSNd",
            },
            href: "https://api.spotify.com/v1/artists/2SrSdSvpminqmStGELCSNd",
            id: "2SrSdSvpminqmStGELCSNd",
            name: "Stormzy",
            type: "artist",
            uri: "spotify:artist:2SrSdSvpminqmStGELCSNd",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/33hSbrSSZZfaXtmEnphHgG",
        },
        href: "https://api.spotify.com/v1/albums/33hSbrSSZZfaXtmEnphHgG",
        id: "33hSbrSSZZfaXtmEnphHgG",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273b704ec9f9085510b34ce1185",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02b704ec9f9085510b34ce1185",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851b704ec9f9085510b34ce1185",
            width: 64,
          },
        ],
        name: "Cry No More (feat. Stormzy & Tay Keith)",
        release_date: "2024-04-19",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:33hSbrSSZZfaXtmEnphHgG",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6UCQYrcJ6wab6gnQ89OJFh",
          },
          href: "https://api.spotify.com/v1/artists/6UCQYrcJ6wab6gnQ89OJFh",
          id: "6UCQYrcJ6wab6gnQ89OJFh",
          name: "Headie One",
          type: "artist",
          uri: "spotify:artist:6UCQYrcJ6wab6gnQ89OJFh",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/2SrSdSvpminqmStGELCSNd",
          },
          href: "https://api.spotify.com/v1/artists/2SrSdSvpminqmStGELCSNd",
          id: "2SrSdSvpminqmStGELCSNd",
          name: "Stormzy",
          type: "artist",
          uri: "spotify:artist:2SrSdSvpminqmStGELCSNd",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5xkFVS6IwwgHEAaRzXc9U3",
          },
          href: "https://api.spotify.com/v1/artists/5xkFVS6IwwgHEAaRzXc9U3",
          id: "5xkFVS6IwwgHEAaRzXc9U3",
          name: "Tay Keith",
          type: "artist",
          uri: "spotify:artist:5xkFVS6IwwgHEAaRzXc9U3",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "PR",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
      ],
      disc_number: 1,
      duration_ms: 204170,
      explicit: true,
      external_ids: {
        isrc: "GBARL2400420",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/1RAwKDC2VKpxLy6es0KZTJ",
      },
      href: "https://api.spotify.com/v1/tracks/1RAwKDC2VKpxLy6es0KZTJ",
      id: "1RAwKDC2VKpxLy6es0KZTJ",
      is_local: false,
      name: "Cry No More (feat. Stormzy & Tay Keith)",
      popularity: 73,
      preview_url:
        "https://p.scdn.co/mp3-preview/8f28a153860c8d8b2331b1f1e80a8ea21aa1d10c?cid=7116f40f98d64f5cbb9e2aafb2209702",
      track_number: 1,
      type: "track",
      uri: "spotify:track:1RAwKDC2VKpxLy6es0KZTJ",
    },
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/6UCQYrcJ6wab6gnQ89OJFh",
      },
      href: "https://api.spotify.com/v1/artists/6UCQYrcJ6wab6gnQ89OJFh",
      id: "6UCQYrcJ6wab6gnQ89OJFh",
      name: "Headie One",
      type: "artist",
      uri: "spotify:artist:6UCQYrcJ6wab6gnQ89OJFh",
    },
    setName: "Headie One",
    relatedArtistName: null,
  },
  "Dua Lipa": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we",
      },
      followers: {
        href: null,
        total: 43463410,
      },
      genres: ["dance pop", "pop", "uk pop"],
      href: "https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we",
      id: "6M2wZ9GZgrQXHCFfjv46we",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb0c68f6c95232e716f0abee8d",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051740c68f6c95232e716f0abee8d",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1780c68f6c95232e716f0abee8d",
          width: 160,
        },
      ],
      name: "Dua Lipa",
      popularity: 87,
      type: "artist",
      uri: "spotify:artist:6M2wZ9GZgrQXHCFfjv46we",
    },
    setName: "Dua Lipa",
    relatedArtistName: null,
  },
  "The Streets": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/4GvOygVQquMaPm8oAc0vXi",
      },
      followers: {
        href: null,
        total: 486242,
      },
      genres: ["birmingham hip hop", "uk garage"],
      href: "https://api.spotify.com/v1/artists/4GvOygVQquMaPm8oAc0vXi",
      id: "4GvOygVQquMaPm8oAc0vXi",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb4b7d7580bc3796bb446537fb",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051744b7d7580bc3796bb446537fb",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1784b7d7580bc3796bb446537fb",
          width: 160,
        },
      ],
      name: "The Streets",
      popularity: 54,
      type: "artist",
      uri: "spotify:artist:4GvOygVQquMaPm8oAc0vXi",
    },
    setName: "The Streets",
    relatedArtistName: null,
  },
  Jungle: {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/59oA5WbbQvomJz2BuRG071",
      },
      followers: {
        href: null,
        total: 1370110,
      },
      genres: ["indie soul", "uk contemporary r&b"],
      href: "https://api.spotify.com/v1/artists/59oA5WbbQvomJz2BuRG071",
      id: "59oA5WbbQvomJz2BuRG071",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb21f6e9ccd576bb2ef541a3fe",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab6761610000517421f6e9ccd576bb2ef541a3fe",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f17821f6e9ccd576bb2ef541a3fe",
          width: 160,
        },
      ],
      name: "Jungle",
      popularity: 73,
      type: "artist",
      uri: "spotify:artist:59oA5WbbQvomJz2BuRG071",
    },
    setName: "Jungle",
    relatedArtistName: null,
  },
  "Sofia Kourtesis": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/7wXTWO45lqpUejDkike0Gf",
      },
      followers: {
        href: null,
        total: 66018,
      },
      genres: ["experimental house"],
      href: "https://api.spotify.com/v1/artists/7wXTWO45lqpUejDkike0Gf",
      id: "7wXTWO45lqpUejDkike0Gf",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebbdb298d141ee49f7be5751a4",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174bdb298d141ee49f7be5751a4",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178bdb298d141ee49f7be5751a4",
          width: 160,
        },
      ],
      name: "Sofia Kourtesis",
      popularity: 46,
      type: "artist",
      uri: "spotify:artist:7wXTWO45lqpUejDkike0Gf",
    },
    setName: "Sofia Kourtesis",
    relatedArtistName: null,
  },
  "London Grammar": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/3Bd1cgCjtCI32PYvDC3ynO",
      },
      followers: {
        href: null,
        total: 1527667,
      },
      genres: ["metropopolis", "nottingham indie"],
      href: "https://api.spotify.com/v1/artists/3Bd1cgCjtCI32PYvDC3ynO",
      id: "3Bd1cgCjtCI32PYvDC3ynO",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb03fca863ba2e1e379ad19998",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab6761610000517403fca863ba2e1e379ad19998",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f17803fca863ba2e1e379ad19998",
          width: 160,
        },
      ],
      name: "London Grammar",
      popularity: 63,
      type: "artist",
      uri: "spotify:artist:3Bd1cgCjtCI32PYvDC3ynO",
    },
    setName: "London Grammar",
    relatedArtistName: null,
  },
  Disclosure: {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/6nS5roXSAGhTGr34W6n7Et",
      },
      followers: {
        href: null,
        total: 2173031,
      },
      genres: ["edm", "electropop", "house", "indietronica", "uk dance"],
      href: "https://api.spotify.com/v1/artists/6nS5roXSAGhTGr34W6n7Et",
      id: "6nS5roXSAGhTGr34W6n7Et",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebc7150fb3cbf60e201ae90840",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174c7150fb3cbf60e201ae90840",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178c7150fb3cbf60e201ae90840",
          width: 160,
        },
      ],
      name: "Disclosure",
      popularity: 71,
      type: "artist",
      uri: "spotify:artist:6nS5roXSAGhTGr34W6n7Et",
    },
    setName: "Disclosure",
    relatedArtistName: null,
  },
  "Peggy Gou": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/2mLA48B366zkELXYx7hcDN",
      },
      followers: {
        href: null,
        total: 922555,
      },
      genres: ["electra", "float house"],
      href: "https://api.spotify.com/v1/artists/2mLA48B366zkELXYx7hcDN",
      id: "2mLA48B366zkELXYx7hcDN",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebffbd43b1e54eb09a8c824f53",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174ffbd43b1e54eb09a8c824f53",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178ffbd43b1e54eb09a8c824f53",
          width: 160,
        },
      ],
      name: "Peggy Gou",
      popularity: 67,
      type: "artist",
      uri: "spotify:artist:2mLA48B366zkELXYx7hcDN",
    },
    setName: "Peggy Gou",
    relatedArtistName: null,
  },
  Romy: {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/3X2DdnmoANw8Rg8luHyZQb",
      },
      followers: {
        href: null,
        total: 110331,
      },
      genres: [],
      href: "https://api.spotify.com/v1/artists/3X2DdnmoANw8Rg8luHyZQb",
      id: "3X2DdnmoANw8Rg8luHyZQb",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebef66595edf6f913e0f7c5b93",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174ef66595edf6f913e0f7c5b93",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178ef66595edf6f913e0f7c5b93",
          width: 160,
        },
      ],
      name: "Romy",
      popularity: 55,
      type: "artist",
      uri: "spotify:artist:3X2DdnmoANw8Rg8luHyZQb",
    },
    setName: "Romy",
    relatedArtistName: null,
  },
  "Shania Twain": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/5e4Dhzv426EvQe3aDb64jL",
      },
      followers: {
        href: null,
        total: 3021228,
      },
      genres: [
        "canadian country",
        "canadian pop",
        "contemporary country",
        "country",
        "country dawn",
      ],
      href: "https://api.spotify.com/v1/artists/5e4Dhzv426EvQe3aDb64jL",
      id: "5e4Dhzv426EvQe3aDb64jL",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb01022f4092cb96e0a91811a5",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab6761610000517401022f4092cb96e0a91811a5",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f17801022f4092cb96e0a91811a5",
          width: 160,
        },
      ],
      name: "Shania Twain",
      popularity: 70,
      type: "artist",
      uri: "spotify:artist:5e4Dhzv426EvQe3aDb64jL",
    },
    setName: "Shania Twain",
    relatedArtistName: null,
  },
  "Jamie XX": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/7A0awCXkE1FtSU8B0qwOJQ",
      },
      followers: {
        href: null,
        total: 799120,
      },
      genres: ["electronica", "future garage", "indie soul", "indietronica"],
      href: "https://api.spotify.com/v1/artists/7A0awCXkE1FtSU8B0qwOJQ",
      id: "7A0awCXkE1FtSU8B0qwOJQ",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb471606bab886f33a4804fa8b",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174471606bab886f33a4804fa8b",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178471606bab886f33a4804fa8b",
          width: 160,
        },
      ],
      name: "Jamie xx",
      popularity: 59,
      type: "artist",
      uri: "spotify:artist:7A0awCXkE1FtSU8B0qwOJQ",
    },
    setName: "Jamie XX",
    relatedArtistName: null,
  },
  "Two Door Cinema Club": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/536BYVgOnRky0xjsPT96zl",
      },
      followers: {
        href: null,
        total: 2394010,
      },
      genres: [
        "indie rock",
        "indietronica",
        "irish rock",
        "modern alternative rock",
        "modern rock",
        "northern irish indie",
      ],
      href: "https://api.spotify.com/v1/artists/536BYVgOnRky0xjsPT96zl",
      id: "536BYVgOnRky0xjsPT96zl",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb86faeb97a905a571b2c361a0",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab6761610000517486faeb97a905a571b2c361a0",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f17886faeb97a905a571b2c361a0",
          width: 160,
        },
      ],
      name: "Two Door Cinema Club",
      popularity: 67,
      type: "artist",
      uri: "spotify:artist:536BYVgOnRky0xjsPT96zl",
    },
    setName: "Two Door Cinema Club",
    relatedArtistName: null,
  },
  "Bombay Bicycle Club": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV",
      },
      followers: {
        href: null,
        total: 865254,
      },
      genres: [
        "british indie rock",
        "chamber pop",
        "indie rock",
        "indietronica",
        "modern rock",
        "shimmer pop",
      ],
      href: "https://api.spotify.com/v1/artists/3pTE9iaJTkWns3mxpNQlJV",
      id: "3pTE9iaJTkWns3mxpNQlJV",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebe210b053175600ecb893bf93",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174e210b053175600ecb893bf93",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178e210b053175600ecb893bf93",
          width: 160,
        },
      ],
      name: "Bombay Bicycle Club",
      popularity: 54,
      type: "artist",
      uri: "spotify:artist:3pTE9iaJTkWns3mxpNQlJV",
    },
    setName: "Bombay Bicycle Club",
    relatedArtistName: null,
  },
  "Arlo Parks": {
    artist: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/4kIwETcbpuFgRukE8o7Opx",
      },
      followers: {
        href: null,
        total: 607796,
      },
      genres: ["indie pop", "indie soul", "uk contemporary r&b"],
      href: "https://api.spotify.com/v1/artists/4kIwETcbpuFgRukE8o7Opx",
      id: "4kIwETcbpuFgRukE8o7Opx",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb7c655a5e51f4eb6e72a61b52",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051747c655a5e51f4eb6e72a61b52",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1787c655a5e51f4eb6e72a61b52",
          width: 160,
        },
      ],
      name: "Arlo Parks",
      popularity: 57,
      type: "artist",
      uri: "spotify:artist:4kIwETcbpuFgRukE8o7Opx",
    },
    setName: "Arlo Parks",
    relatedArtistName: null,
  },
};
